version: "3.3"
services:
  users:
    image: halahkr/users_average
    ports:
      - "9005:9005"
  buildings:
    image: halahkr/buildings_average
    ports:
      - "8005:8005"
  average:
    image: halahkr/average_age
    ports:
      - "8080:8080"
    links:
      - users
      - buildings
